<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PreguntaOpcion', 'doctrine');

/**
 * BasePreguntaOpcion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $etiqueta
 * 
 * @method integer        getId()       Returns the current record's "id" value
 * @method string         getEtiqueta() Returns the current record's "etiqueta" value
 * @method PreguntaOpcion setId()       Sets the current record's "id" value
 * @method PreguntaOpcion setEtiqueta() Sets the current record's "etiqueta" value
 * 
 * @package    encuesta-doctrine
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePreguntaOpcion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pregunta_opcion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('etiqueta', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}