<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PreguntaColumnaOpcion', 'doctrine');

/**
 * BasePreguntaColumnaOpcion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $etiqueta
 * @property integer $id_pregunta_columna
 * @property PreguntaColumna $PreguntaColumna
 * 
 * @method integer               getId()                  Returns the current record's "id" value
 * @method string                getEtiqueta()            Returns the current record's "etiqueta" value
 * @method integer               getIdPreguntaColumna()   Returns the current record's "id_pregunta_columna" value
 * @method PreguntaColumna       getPreguntaColumna()     Returns the current record's "PreguntaColumna" value
 * @method PreguntaColumnaOpcion setId()                  Sets the current record's "id" value
 * @method PreguntaColumnaOpcion setEtiqueta()            Sets the current record's "etiqueta" value
 * @method PreguntaColumnaOpcion setIdPreguntaColumna()   Sets the current record's "id_pregunta_columna" value
 * @method PreguntaColumnaOpcion setPreguntaColumna()     Sets the current record's "PreguntaColumna" value
 * 
 * @package    encuesta-doctrine
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePreguntaColumnaOpcion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pregunta_columna_opcion');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('etiqueta', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('id_pregunta_columna', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PreguntaColumna', array(
             'local' => 'id_pregunta_columna',
             'foreign' => 'id'));
    }
}