<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TipoEncuesta', 'doctrine');

/**
 * BaseTipoEncuesta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $etiqueta
 * @property Doctrine_Collection $Encuesta
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getEtiqueta() Returns the current record's "etiqueta" value
 * @method Doctrine_Collection getEncuesta() Returns the current record's "Encuesta" collection
 * @method TipoEncuesta        setId()       Sets the current record's "id" value
 * @method TipoEncuesta        setEtiqueta() Sets the current record's "etiqueta" value
 * @method TipoEncuesta        setEncuesta() Sets the current record's "Encuesta" collection
 * 
 * @package    encuesta-doctrine
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTipoEncuesta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_encuesta');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('etiqueta', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Encuesta', array(
             'local' => 'id',
             'foreign' => 'id_tipo_encuesta'));
    }
}