<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PreguntaAtributo', 'doctrine');

/**
 * BasePreguntaAtributo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_tipo_atributo
 * @property integer $id_pregunta
 * @property integer $valor
 * @property TipoAtributo $TipoAtributo
 * @property Pregunta $Pregunta
 * 
 * @method integer          getId()               Returns the current record's "id" value
 * @method integer          getIdTipoAtributo()   Returns the current record's "id_tipo_atributo" value
 * @method integer          getIdPregunta()       Returns the current record's "id_pregunta" value
 * @method integer          getValor()            Returns the current record's "valor" value
 * @method TipoAtributo     getTipoAtributo()     Returns the current record's "TipoAtributo" value
 * @method Pregunta         getPregunta()         Returns the current record's "Pregunta" value
 * @method PreguntaAtributo setId()               Sets the current record's "id" value
 * @method PreguntaAtributo setIdTipoAtributo()   Sets the current record's "id_tipo_atributo" value
 * @method PreguntaAtributo setIdPregunta()       Sets the current record's "id_pregunta" value
 * @method PreguntaAtributo setValor()            Sets the current record's "valor" value
 * @method PreguntaAtributo setTipoAtributo()     Sets the current record's "TipoAtributo" value
 * @method PreguntaAtributo setPregunta()         Sets the current record's "Pregunta" value
 * 
 * @package    encuesta-doctrine
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePreguntaAtributo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pregunta_atributo');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('id_tipo_atributo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('id_pregunta', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('valor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoAtributo', array(
             'local' => 'id_tipo_atributo',
             'foreign' => 'id'));

        $this->hasOne('Pregunta', array(
             'local' => 'id_pregunta',
             'foreign' => 'id'));
    }
}