<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Encuesta', 'doctrine');

/**
 * BaseEncuesta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $etiqueta
 * @property string $descripcion
 * @property string $bienvenida
 * @property string $despedida
 * @property string $template
 * @property string $nombre_responsable
 * @property date $fecha_inicio
 * @property date $fecha_expiracion
 * @property integer $id_organizacion
 * @property integer $id_tipo_encuesta
 * @property TipoEncuesta $TipoEncuesta
 * @property Organizacion $Organizacion
 * @property Doctrine_Collection $EncuestaGrupoUsuario
 * @property Doctrine_Collection $Encuestado
 * @property Doctrine_Collection $GrupoPregunta
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method string              getEtiqueta()             Returns the current record's "etiqueta" value
 * @method string              getDescripcion()          Returns the current record's "descripcion" value
 * @method string              getBienvenida()           Returns the current record's "bienvenida" value
 * @method string              getDespedida()            Returns the current record's "despedida" value
 * @method string              getTemplate()             Returns the current record's "template" value
 * @method string              getNombreResponsable()    Returns the current record's "nombre_responsable" value
 * @method date                getFechaInicio()          Returns the current record's "fecha_inicio" value
 * @method date                getFechaExpiracion()      Returns the current record's "fecha_expiracion" value
 * @method integer             getIdOrganizacion()       Returns the current record's "id_organizacion" value
 * @method integer             getIdTipoEncuesta()       Returns the current record's "id_tipo_encuesta" value
 * @method TipoEncuesta        getTipoEncuesta()         Returns the current record's "TipoEncuesta" value
 * @method Organizacion        getOrganizacion()         Returns the current record's "Organizacion" value
 * @method Doctrine_Collection getEncuestaGrupoUsuario() Returns the current record's "EncuestaGrupoUsuario" collection
 * @method Doctrine_Collection getEncuestado()           Returns the current record's "Encuestado" collection
 * @method Doctrine_Collection getGrupoPregunta()        Returns the current record's "GrupoPregunta" collection
 * @method Encuesta            setId()                   Sets the current record's "id" value
 * @method Encuesta            setEtiqueta()             Sets the current record's "etiqueta" value
 * @method Encuesta            setDescripcion()          Sets the current record's "descripcion" value
 * @method Encuesta            setBienvenida()           Sets the current record's "bienvenida" value
 * @method Encuesta            setDespedida()            Sets the current record's "despedida" value
 * @method Encuesta            setTemplate()             Sets the current record's "template" value
 * @method Encuesta            setNombreResponsable()    Sets the current record's "nombre_responsable" value
 * @method Encuesta            setFechaInicio()          Sets the current record's "fecha_inicio" value
 * @method Encuesta            setFechaExpiracion()      Sets the current record's "fecha_expiracion" value
 * @method Encuesta            setIdOrganizacion()       Sets the current record's "id_organizacion" value
 * @method Encuesta            setIdTipoEncuesta()       Sets the current record's "id_tipo_encuesta" value
 * @method Encuesta            setTipoEncuesta()         Sets the current record's "TipoEncuesta" value
 * @method Encuesta            setOrganizacion()         Sets the current record's "Organizacion" value
 * @method Encuesta            setEncuestaGrupoUsuario() Sets the current record's "EncuestaGrupoUsuario" collection
 * @method Encuesta            setEncuestado()           Sets the current record's "Encuestado" collection
 * @method Encuesta            setGrupoPregunta()        Sets the current record's "GrupoPregunta" collection
 * 
 * @package    encuesta-doctrine
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseEncuesta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('encuesta');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('etiqueta', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('bienvenida', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('despedida', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('template', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('nombre_responsable', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('fecha_inicio', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('fecha_expiracion', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('id_organizacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('id_tipo_encuesta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoEncuesta', array(
             'local' => 'id_tipo_encuesta',
             'foreign' => 'id'));

        $this->hasOne('Organizacion', array(
             'local' => 'id_organizacion',
             'foreign' => 'id'));

        $this->hasMany('EncuestaGrupoUsuario', array(
             'local' => 'id',
             'foreign' => 'id_encuesta'));

        $this->hasMany('Encuestado', array(
             'local' => 'id',
             'foreign' => 'id_encuesta'));

        $this->hasMany('GrupoPregunta', array(
             'local' => 'id',
             'foreign' => 'id_encuesta'));
    }
}