<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Organizacion', 'doctrine');

/**
 * BaseOrganizacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $etiqueta
 * @property Doctrine_Collection $Encuesta
 * @property Doctrine_Collection $GrupoUsuario
 * @property Doctrine_Collection $UsuarioOrganizacion
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getEtiqueta()            Returns the current record's "etiqueta" value
 * @method Doctrine_Collection getEncuesta()            Returns the current record's "Encuesta" collection
 * @method Doctrine_Collection getGrupoUsuario()        Returns the current record's "GrupoUsuario" collection
 * @method Doctrine_Collection getUsuarioOrganizacion() Returns the current record's "UsuarioOrganizacion" collection
 * @method Organizacion        setId()                  Sets the current record's "id" value
 * @method Organizacion        setEtiqueta()            Sets the current record's "etiqueta" value
 * @method Organizacion        setEncuesta()            Sets the current record's "Encuesta" collection
 * @method Organizacion        setGrupoUsuario()        Sets the current record's "GrupoUsuario" collection
 * @method Organizacion        setUsuarioOrganizacion() Sets the current record's "UsuarioOrganizacion" collection
 * 
 * @package    encuesta-doctrine
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseOrganizacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('organizacion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('etiqueta', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Encuesta', array(
             'local' => 'id',
             'foreign' => 'id_organizacion'));

        $this->hasMany('GrupoUsuario', array(
             'local' => 'id',
             'foreign' => 'id_organizacion'));

        $this->hasMany('UsuarioOrganizacion', array(
             'local' => 'id',
             'foreign' => 'id_organizacion'));
    }
}