<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TipoPregunta', 'doctrine');

/**
 * BaseTipoPregunta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $etiqueta
 * @property Doctrine_Collection $Pregunta
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getEtiqueta() Returns the current record's "etiqueta" value
 * @method Doctrine_Collection getPregunta() Returns the current record's "Pregunta" collection
 * @method TipoPregunta        setId()       Sets the current record's "id" value
 * @method TipoPregunta        setEtiqueta() Sets the current record's "etiqueta" value
 * @method TipoPregunta        setPregunta() Sets the current record's "Pregunta" collection
 * 
 * @package    encuesta-doctrine
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTipoPregunta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_pregunta');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('etiqueta', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Pregunta', array(
             'local' => 'id',
             'foreign' => 'id_tipo_pregunta'));
    }
}