<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TipoAtributo', 'doctrine');

/**
 * BaseTipoAtributo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $etiqueta
 * @property Doctrine_Collection $PreguntaAtributo
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getEtiqueta()         Returns the current record's "etiqueta" value
 * @method Doctrine_Collection getPreguntaAtributo() Returns the current record's "PreguntaAtributo" collection
 * @method TipoAtributo        setId()               Sets the current record's "id" value
 * @method TipoAtributo        setEtiqueta()         Sets the current record's "etiqueta" value
 * @method TipoAtributo        setPreguntaAtributo() Sets the current record's "PreguntaAtributo" collection
 * 
 * @package    encuesta-doctrine
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTipoAtributo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_atributo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('etiqueta', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PreguntaAtributo', array(
             'local' => 'id',
             'foreign' => 'id_tipo_atributo'));
    }
}