<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Usuario', 'doctrine');

/**
 * BaseUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $login
 * @property string $password
 * @property string $nombre_completo
 * @property string $correo
 * @property integer $id_tipo_usuario
 * @property TipoUsuario $TipoUsuario
 * @property Doctrine_Collection $UsuarioOrganizacion
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getLogin()               Returns the current record's "login" value
 * @method string              getPassword()            Returns the current record's "password" value
 * @method string              getNombreCompleto()      Returns the current record's "nombre_completo" value
 * @method string              getCorreo()              Returns the current record's "correo" value
 * @method integer             getIdTipoUsuario()       Returns the current record's "id_tipo_usuario" value
 * @method TipoUsuario         getTipoUsuario()         Returns the current record's "TipoUsuario" value
 * @method Doctrine_Collection getUsuarioOrganizacion() Returns the current record's "UsuarioOrganizacion" collection
 * @method Usuario             setId()                  Sets the current record's "id" value
 * @method Usuario             setLogin()               Sets the current record's "login" value
 * @method Usuario             setPassword()            Sets the current record's "password" value
 * @method Usuario             setNombreCompleto()      Sets the current record's "nombre_completo" value
 * @method Usuario             setCorreo()              Sets the current record's "correo" value
 * @method Usuario             setIdTipoUsuario()       Sets the current record's "id_tipo_usuario" value
 * @method Usuario             setTipoUsuario()         Sets the current record's "TipoUsuario" value
 * @method Usuario             setUsuarioOrganizacion() Sets the current record's "UsuarioOrganizacion" collection
 * 
 * @package    encuesta-doctrine
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('login', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '40',
             ));
        $this->hasColumn('password', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '40',
             ));
        $this->hasColumn('nombre_completo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('correo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('id_tipo_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoUsuario', array(
             'local' => 'id_tipo_usuario',
             'foreign' => 'id'));

        $this->hasMany('UsuarioOrganizacion', array(
             'local' => 'id',
             'foreign' => 'id_usuario'));
    }
}