<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GrupoUsuario', 'doctrine');

/**
 * BaseGrupoUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $etiqueta
 * @property integer $id_organizacion
 * @property Organizacion $Organizacion
 * @property Doctrine_Collection $EncuestaGrupoUsuario
 * @property Doctrine_Collection $EncuestadoGrupoUsuario
 * 
 * @method integer             getId()                     Returns the current record's "id" value
 * @method string              getEtiqueta()               Returns the current record's "etiqueta" value
 * @method integer             getIdOrganizacion()         Returns the current record's "id_organizacion" value
 * @method Organizacion        getOrganizacion()           Returns the current record's "Organizacion" value
 * @method Doctrine_Collection getEncuestaGrupoUsuario()   Returns the current record's "EncuestaGrupoUsuario" collection
 * @method Doctrine_Collection getEncuestadoGrupoUsuario() Returns the current record's "EncuestadoGrupoUsuario" collection
 * @method GrupoUsuario        setId()                     Sets the current record's "id" value
 * @method GrupoUsuario        setEtiqueta()               Sets the current record's "etiqueta" value
 * @method GrupoUsuario        setIdOrganizacion()         Sets the current record's "id_organizacion" value
 * @method GrupoUsuario        setOrganizacion()           Sets the current record's "Organizacion" value
 * @method GrupoUsuario        setEncuestaGrupoUsuario()   Sets the current record's "EncuestaGrupoUsuario" collection
 * @method GrupoUsuario        setEncuestadoGrupoUsuario() Sets the current record's "EncuestadoGrupoUsuario" collection
 * 
 * @package    encuesta-doctrine
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseGrupoUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grupo_usuario');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('etiqueta', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('id_organizacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Organizacion', array(
             'local' => 'id_organizacion',
             'foreign' => 'id'));

        $this->hasMany('EncuestaGrupoUsuario', array(
             'local' => 'id',
             'foreign' => 'id_grupo_usuario'));

        $this->hasMany('EncuestadoGrupoUsuario', array(
             'local' => 'id',
             'foreign' => 'id_grupo_usuario'));
    }
}