<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Pregunta', 'doctrine');

/**
 * BasePregunta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $etiqueta
 * @property string $pregunta
 * @property integer $orden
 * @property timestamp $fecha_modificacion
 * @property integer $obligatoria
 * @property integer $id_grupo_pregunta
 * @property integer $id_tipo_pregunta
 * @property GrupoPregunta $GrupoPregunta
 * @property TipoPregunta $TipoPregunta
 * @property Doctrine_Collection $PreguntaAtributo
 * @property Doctrine_Collection $PreguntaColumna
 * @property Doctrine_Collection $PreguntaFila
 * @property Doctrine_Collection $PreguntaRespuesta
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getEtiqueta()           Returns the current record's "etiqueta" value
 * @method string              getPregunta()           Returns the current record's "pregunta" value
 * @method integer             getOrden()              Returns the current record's "orden" value
 * @method timestamp           getFechaModificacion()  Returns the current record's "fecha_modificacion" value
 * @method integer             getObligatoria()        Returns the current record's "obligatoria" value
 * @method integer             getIdGrupoPregunta()    Returns the current record's "id_grupo_pregunta" value
 * @method integer             getIdTipoPregunta()     Returns the current record's "id_tipo_pregunta" value
 * @method GrupoPregunta       getGrupoPregunta()      Returns the current record's "GrupoPregunta" value
 * @method TipoPregunta        getTipoPregunta()       Returns the current record's "TipoPregunta" value
 * @method Doctrine_Collection getPreguntaAtributo()   Returns the current record's "PreguntaAtributo" collection
 * @method Doctrine_Collection getPreguntaColumna()    Returns the current record's "PreguntaColumna" collection
 * @method Doctrine_Collection getPreguntaFila()       Returns the current record's "PreguntaFila" collection
 * @method Doctrine_Collection getPreguntaRespuesta()  Returns the current record's "PreguntaRespuesta" collection
 * @method Pregunta            setId()                 Sets the current record's "id" value
 * @method Pregunta            setEtiqueta()           Sets the current record's "etiqueta" value
 * @method Pregunta            setPregunta()           Sets the current record's "pregunta" value
 * @method Pregunta            setOrden()              Sets the current record's "orden" value
 * @method Pregunta            setFechaModificacion()  Sets the current record's "fecha_modificacion" value
 * @method Pregunta            setObligatoria()        Sets the current record's "obligatoria" value
 * @method Pregunta            setIdGrupoPregunta()    Sets the current record's "id_grupo_pregunta" value
 * @method Pregunta            setIdTipoPregunta()     Sets the current record's "id_tipo_pregunta" value
 * @method Pregunta            setGrupoPregunta()      Sets the current record's "GrupoPregunta" value
 * @method Pregunta            setTipoPregunta()       Sets the current record's "TipoPregunta" value
 * @method Pregunta            setPreguntaAtributo()   Sets the current record's "PreguntaAtributo" collection
 * @method Pregunta            setPreguntaColumna()    Sets the current record's "PreguntaColumna" collection
 * @method Pregunta            setPreguntaFila()       Sets the current record's "PreguntaFila" collection
 * @method Pregunta            setPreguntaRespuesta()  Sets the current record's "PreguntaRespuesta" collection
 * 
 * @package    encuesta-doctrine
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePregunta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pregunta');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('etiqueta', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('pregunta', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('orden', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('fecha_modificacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('obligatoria', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('id_grupo_pregunta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('id_tipo_pregunta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GrupoPregunta', array(
             'local' => 'id_grupo_pregunta',
             'foreign' => 'id'));

        $this->hasOne('TipoPregunta', array(
             'local' => 'id_tipo_pregunta',
             'foreign' => 'id'));

        $this->hasMany('PreguntaAtributo', array(
             'local' => 'id',
             'foreign' => 'id_pregunta'));

        $this->hasMany('PreguntaColumna', array(
             'local' => 'id',
             'foreign' => 'id_pregunta'));

        $this->hasMany('PreguntaFila', array(
             'local' => 'id',
             'foreign' => 'id_pregunta'));

        $this->hasMany('PreguntaRespuesta', array(
             'local' => 'id',
             'foreign' => 'id_pregunta'));
    }
}