<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/12/28 20:51:46
sfConfig::add(array(
  'mod_default_enabled' => true,
  'mod_default_view_class' => 'sfPHP',
  'mod_default_is_internal' => false,
));
