<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/12/28 20:55:03

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=encuestabd',
  'username' => 'encuesta',
  'password' => 'encuesta22',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'doctrine',
)),);
